risk/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'login/$', views.user_login, name='login'),
	url(r'register/$', views.register, name='register'),
	url(r'logout/$', views.user_logout, name='logout'),
]

risk/reports/urls.py
from django.conf.urls import url
from .views import ReportDetail, ReportList

urlpatterns = [
	url(r'^$', ReportList.as_view(), name="report_list"),
	url(r'^(?P<pk>[0-9]+)/$', ReportDetail.as_view(), name="report_detail"),
]

risk/risk/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
]

risk/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
	user = models.ForeignKey(User, related_name='profile')
	location = models.CharField(max_length=150, blank=False, null=False)

	class Meta:
		permissions = (('customer_permission', 'Customers have permission to receove mail'),)

	def __str__(self):
		return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
# 	if created:
# 		Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
# 	instance.profile.save()

risk/reports/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class Report(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=200)
	location = models.CharField(max_length=100)
	# slug = models.SlugField(unique=True)
	category = models.CharField(max_length=100, blank=False, null=False)
	description = models.TextField()
	advice = models.TextField()


	def __str__(self):
		return self.title

	def get_absolute_url(self, id):
		return reverse("reports:report_detail", kwargs={"id":self.id})

class ReportLoc(models.Model):
	report = models.OneToOneField(Report)
	latitude = models.DecimalField(max_digits=8, decimal_places=4)
	longitude = models.DecimalField(max_digits=8, decimal_places=4)

	def __str__(self):
		return self.report.title


		

risk/accounts/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

# class LocationMixin(forms.ModelForm):
# 	class Meta:
# 		model = Profile
# 		fields = ('location',)
# 		widgets = {
# 			'location': forms.TextInput()
# 		}



class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'username', 'email', 'password')

class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('location',)
	
	# def clean_password2(self):
	# 	cd = self.cleaned_data
	# 	if cd['password'] != cd['password2']:
	# 		raise forms.ValidationError('passwords don\'t match.')
	# 	return cd['password2']


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

risk/reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
	class Meta:
		model = Report
		fields = ('title', 'location', 'category', 'description', 'advice')

risk/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext

from .forms import LoginForm,UserForm, ProfileForm
from .models import Profile

# Create your views here.

def register(request):
	context = RequestContext(request)
	registered = False

	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = ProfileForm(request.POST)
		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()
			registered = True

			return HttpResponse('success')

	else:
		user_form = UserForm()
		profile_form = ProfileForm()
	return render(request, 'accounts/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})



def user_login(request):
	current_user = request.user

	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(username=cd['username'], password=cd['password'])
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect('reports/index.html')
				else :
					return HttpResponse('Disabled account')
			else:
				return HttpResponse('Invalid account')
	else:
		form = LoginForm()

	return render(request, 'accounts/login.html', {'form': form})

@login_required
def user_logout(request):
	logout(request)

	return HttpResponseRedirect('accounts/login/')

risk/reports/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.db.models import Q
from .models import Report, ReportLoc

from accounts.models import Profile
# Create your views here.

# def report_list_view(request):
# 	current_user_loc = request.user.profile.get().location
# 	qs = Report.objects.filter(Q(location__icontains=current_user_loc))
# 	#latest_reports = Report.objects.all(Q(location__icontains=cure))
# 	template = 'reports/list.html'
# 	context = {"queryset": qs, "current_loc": current_user_loc}
# 	return render(request, template, context)

# def report_detail_view(request, id):
# 	report = get_object_or_404(Report, id=id)
# 	template = 'reports/detail.html'
# 	context = {"reports_list": report}
# 	return render(request, template, context)

class ReportList(ListView):
	model = Report

	# queryset = Report.objects.filter(Q(location__icontains='nepal'))
	context_object_name='reports'
	template_name = 'list.html'

	def get_queryset(self):
		user_loc = self.request.user.profile.get().location
		qs = super().get_queryset()
		return qs.filter(Q(location__icontains=user_loc))


class ReportDetail(DetailView):
	model = Report
	
	# loc_qs = loc.filter(id=id)
	# context_object_name = 'report'
	# template_name = 'reports/detail.html'
	# pk_url_kwarg = 'report_id'
	def get_context_data(self, *args, **kwargs):
		context = super(ReportDetail, self).get_context_data(*args, **kwargs)
		report_pk = self.kwargs.get("pk")
		loc = get_object_or_404(ReportLoc, pk=report_pk)
		context["lat"] = loc.latitude
		context["long"] = loc.longitude
		return context






	

risk/templates/accounts/login.html
<html>
	<head>
		<title>Login</title>
	</head>

	<body>

		{% if user.is_authenticated %}
			<h1>Hello, {{ user.username }}. You are logged in.</h1>
			<h4>To view Reports, click <a href="{% url "reports:report_list" %}">Here</a>.</h4>
		{% else %}
			<h1>Login: </h1>
			<!-- <h1>{{ user.username }}</h1> -->

			<p>Use the following form to login:</p>

			<form action="." method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<p><input type="submit" value="Log-in"></p>
			</form>

		{% endif %}
	
	</body>
</html>

risk/templates/accounts/register.html
<html>
	<head>
		<title>Login</title>
	</head>

	<body>
		<h1>Register: </h1>

		<p>Use the following form to register a new user:</p>
		<form action="." method="post">
			{{user_form.as_p}}
			{{ profile_form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Create new account">
		</form>
		

		

		
	</body>
</html>

risk/templates/accounts/register_done.html
<html>
	<head>
		<title>Login</title>
	</head>

	<body>
		<h1>Welcome {{ new_user.first_name }} </h1>
		<p>Account has been created. You can now <a href="{% url "login" %}">Login</a>.</p>

	</body>
</html>

risk/templates/reports/index.html
<html>
	<head>
		<title>Report List</title>
	</head>

	<body>
		<h1>Reports List: </h1>

		{% if latest_reports %}

		<ul>
			{% for report in latest_reports %}
			<li> 
				{{ report.title }} <br>
				{{ report.created_at }} <br>
				{{ report.location }} <br>
				{{ report.description }} <br>
				{{ report.advice }} 

			</li>
			<hr>
			{% endfor %}
		</ul>

		{% endif %}

		
	</body>
</html>

risk/templates/reports/list.html
<html>
	<head>
		<title>Report List</title>
	</head>

	<body>

		{% if user.is_authenticated %}
		
		<h1>Reports List: </h1>
		

		{% if latest_reports %}
	
		<ul>
			{% for report in latest_reports %}
			{% if current_loc.location == report.location %}
			<li> 
				<a href="">{{ report.title }}</a> <br>
				{{ report.created_at }} <br>
				{{ report.location }} <br>
				

			</li>
			
			<hr>
			{% endif %}
			{% endfor %}
		</ul>

		{% endif %}

		{% else %}
			<h1>Login <a href="{% url "accounts:login" %}">Here</a></h1>
		{% endif %}

		
	</body>
</html>

risk/templates/reports/report_detail.html
<html>
	<head>
		<title>Report Detail</title>
	</head>

	<body>
		

		

		<h1>Reports Details: </h1>
		
		<span id="lat">{{ lat }}</span> |  <span id="long">{{ long }}</span>
		
		<ul>
			
			<li> 
				{{ object.title }} <br>
				{{ object.created_at }} <br>
				{{ object.location }} <br>
				<span id="rep_desc">{{ object.description }}</span> <br>
				{{ object.advice }} 
				
			</li>
			
			
		</ul>

		<hr>

		<h3>Map Plot:</h3>
		<div id="gmaps" style="width: 400px; height: 400px; background-color: grey;"></div>

		
	<script>
		function initMap() {
			var desc = document.getElementById('rep_desc').innerHTML
			var lat = Number(document.getElementById('lat').innerHTML);
			var long = Number(document.getElementById('long').innerHTML);
			// console.log(lat, long);
			var loc = {lat: lat, lng: long};
			var map = new google.maps.Map(document.getElementById('gmaps'), {
				zoom : 14,
				center : loc
			});
			var marker = new google.maps.Marker({
				position : loc,
				map : map
			});
			var infoWindow = new google.maps.InfoWindow({
				content: desc
			});
			google.maps.event.addListener(marker, 'click', function() {
				infoWindow.open(map, marker);
			});
		}


	</script>
	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgJUurxiT0EIMg9HDoO8vhDFHodnZDKVg&callback=initMap">
    </script>	
	</body>
</html>

risk/templates/reports/report_list.html
<html>
	<head>
		<title>Report List</title>
	</head>

	<body>

		{% if user.is_authenticated %}
		
		<h1>Hello, {{ request.user }}.</h1>
		<!-- {{ request.user.profile.location }} -->
		<h1>Reports List: </h1>
		<!-- {{ current_loc }}
		{{ queryset }} -->
		
		{% if reports %}
	
		<ul>
			{% for query in reports %}
			
			<li> 
				<a href="{% url "reports:report_detail" pk=query.id %}">{{ query.title }}</a> <br>
				{{ query.created_at }} <br>
				{{ query.location }} <br>
				

			</li>
			
			<hr>
			
			{% endfor %}
		</ul>

		{% endif %}

		{% else %}
			<h1>Login <a href="{% url "accounts:login" %}">Here</a></h1>
		{% endif %}

		
	</body>
</html>